import anthropic
import os
import smtplib
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

CLAUDE_API_KEY = os.environ["CLAUDE_API_KEY"]
GMAIL_ADDRESS = os.environ["GMAIL_ADDRESS"]
GMAIL_APP_PASS = os.environ["GMAIL_APP_PASS"]
RECIPIENT_EMAIL = os.environ["RECIPIENT_EMAIL"]

TOPICS = [
    "Klarna news",
    "Affirm news",
    "Afterpay news",
    "BNPL fintech news",
    "Expedia Group news",
    "Hotels.com news",
    "Vrbo news",
    "OTA online travel news",
    "fintech partnerships payments",
    "travel industry trends",
    "Booking Holdings news",
    "Airbnb news",
    "travel fintech BNPL",
    "consumer spending travel",
    "Block Square Afterpay news",
    "fintech regulation CFPB",
]


def fetch_digest():
    today = datetime.now().strftime("%B %d, %Y")
    topic_list = ", ".join(TOPICS)

    prompt = f"""You are a financial and travel industry analyst. Today is {today}.

Search the web for news published in the last 24 hours only across these topics: {topic_list}.

Prioritize these sources when available: Skift, PYMNTS, PhocusWire, TechCrunch, Bloomberg, Reuters, Forbes, Business Insider.

Strict rules:
- Only include stories published today or yesterday ({today})
- Do not include anything older than 48 hours
- Do not repeat stories covered in previous digests
- If there is no new news on a topic today, skip it entirely
- Always include the full URL to the original article

Write a concise daily briefing covering the top 5-8 fresh stories only. For each story:
- Write a bold headline that is a clickable hyperlink in HTML format: <a href="URL">Headline</a>
- 2-3 sentence summary explaining what happened and why it matters
- Source name and exact publish date

Group stories under these two sections:
## BNPL & Fintech
## Expedia & OTA

Keep the tone professional and direct. No filler. Focus on what matters for someone working in BNPL affiliate partnerships at an OTA."""

    client = anthropic.Anthropic(api_key=CLAUDE_API_KEY)

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=3000,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": prompt}],
    )

    text_blocks = [b.text for b in response.content if hasattr(b, "text")]
    return "\n".join(text_blocks).strip()


def send_email(digest_text):
    today = datetime.now().strftime("%B %d, %Y")
    subject = f"Daily Intel Digest — {today}"

    lines = digest_text.split("\n")
    html_lines = []
    for line in lines:
        line = line.strip()
        if not line:
            html_lines.append("<br>")
        elif line.startswith("## "):
            html_lines.append(f"<h2 style='margin-top:28px;border-bottom:1px solid #ddd;padding-bottom:6px;'>{line[3:]}</h2>")
        elif line.startswith("**") and line.endswith("**"):
            html_lines.append(f"<p><strong>{line.strip('**')}</strong></p>")
        else:
            html_lines.append(f"<p style='margin:4px 0;'>{line}</p>")

    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 680px; margin: auto; padding: 32px 24px; color: #111;">
      <h1 style="font-size: 20px; border-bottom: 2px solid #111; padding-bottom: 10px;">Daily Intel Digest</h1>
      <p style="color: #888; font-size: 13px; margin-top: 4px;">{today}</p>
      <div style="margin-top: 24px; font-size: 15px; line-height: 1.7;">
        {"".join(html_lines)}
      </div>
      <p style="margin-top: 40px; font-size: 12px; color: #aaa;">Generated by Claude with live web search.</p>
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = RECIPIENT_EMAIL
    msg.attach(MIMEText(digest_text, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASS)
        server.sendmail(GMAIL_ADDRESS, RECIPIENT_EMAIL, msg.as_string())

    print(f"Email sent to {RECIPIENT_EMAIL}")


def main():
    print("Fetching digest...")
    digest = fetch_digest()
    print("Sending email...")
    send_email(digest)
    print("Done.")


if __name__ == "__main__":
    main()
